### ISSUE TITLE
Drop Good, Fair, Poor on Condition Rule

### ISSUE THREAD

**Issue by kevinhathaway** [RSGInc/HPMS-Score-Card-Generator#1]

**Comment by landisrm** [comment]
Is this on the Pavement: Detailed Review page as Overall Condition

**Comment by ghost** [comment]
That's the one!

**Comment by landisrm** [comment]
add the following summaries in place of the overall condition on the Pavement Detail page:
  a.	Missing through lanes
  b.	Surface type is null
  c.	Surface type = 1 
  d.	Surface type = 11
  e.	Sections lengths greater than 0.11 
  f. We may consider adding “Sections not spatially matching across distress types” at a later point.

**Comment by landisrm** [comment]
These summaries should be separately by 
  - Interstate
  - Non-Interstate NHS
  - Other/Minor Arterials
  - Collectors + Locals 
just like most of the other graphics and tables.

**Comment by landisrm** [comment]
Remember to change page 2 ("how to interpret key scorecard charts") to reflect changes on the pavement detail page

**Comment by kevinhathaway** [comment]
This is a graphic that I created in Adobe Illustrator. I can update as needed.

**Comment by landisrm** [comment]
Don't see the graphic.  is it attached?

**Comment by kevinhathaway** [comment]
How's this?
![page2_revised-01](https://user-images.githubusercontent.com/20462989/26947592-422d1422-4c61-11e7-9e35-77bae8e41f66.png)

**Comment by kevinhathaway** [comment]
![page2_revised-01](https://user-images.githubusercontent.com/20462989/26947653-76fdc4da-4c61-11e7-9c18-fec0dcb27778.png)
